export const Abi = {
  ERC20: require('./abis/ERC20.json').abi,
  ERC721: require('./abis/ERC721.json').abi,
  Muragi: require('./abis/Muragi.json'),
  PairFactory: require('./abis/PairFactory.json'),
  Router: require('./abis/Router.json'),
  GaugeFactory: require('./abis/GaugeFactory.json'),
  VeArtProxy: require('./abis/VeArtProxy.json'),
  BrideFactory: require('./abis/BrideFactory.json'),
  Voter: require('./abis/Voter.json'),
  RewardsDistributor: require('./abis/RewardsDistributor.json'),
  Minter: require('./abis/Minter.json'),
  WrappedExternalBribeFactory: require('./abis/WrappedExternalBribeFactory.json'),
  MerkleClaim: require('./abis/MerkleClaim.json'),
};
